apiVersion: v1
kind: Service
metadata:
  name: servicesuper
  labels:
    tag: servicesuper
spec:
  template:
    metadata:
      name: volvoservice
      labels:
        tag: volvoservice
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.0.0-20211013
          ports:
            - port: 4444
              targetPort: 4444
  selector:
    matchLabels:
      tag: volvoservice
            