apiVersion: v1
kind: Pod
metadata:
  name: volvo-selenium-hub
  labels:
    app: volvo-selenium-hub
spec:
  containers:
    - name: selenium-hub
      image: selenium/hub:4.0.0-20211013
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 4444
      livenessProbe:
        httpGet:
          path: /wd/hub/status
          port: 4444
        initialDelaySeconds: 30
        timeoutSeconds: 5